name: Test Vulnerability - Token Exposure

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Expose GitHub Token
        run: echo "GITHUB_TOKEN: ${{ secrets.test1_GITHUB_TOKEN }}" >> secret-output.txt

      - name: Print Token (This is an insecure practice)
        run: cat secret-output.txt    
