name: Command Injection Test

on:
  workflow_dispatch:
    inputs:
      user_input:
        description: 'Input to be echoed'
        required: true
        default: 'safe'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo user input (vulnerable)
        run: echo "${{ github.event.inputs.user_input }}"
